version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run: gradlew dependencies
      - run: gradlew shadowJar
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - store_artifacts:
          path: build/libs
          destination: libs
#machine:
#  java:
#    version: oraclejdk8
#general:
#  artifacts:
#    - "build/libs/*.jar"
#dependencies:
#  override:
#    - chmod +x gradlew
#    - ./gradlew dependencies
#compile:
#  post:
#    - ./gradlew shadowJar
#    - mkdir -p $CIRCLE_ARTIFACTS/build/libs
#    - cp build/libs/* $CIRCLE_ARTIFACTS/build/libs
#    - if [ $CIRCLE_BRANCH = 'master' ]; then ./gradlew bintrayUpload --stacktrace; fi